apiVersion: v1
kind: Namespace
metadata:
  name: todoapp
---
apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
  namespace: todoapp
spec:
  type: ClusterIP
  selector:
    app: kube2py-blue
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
 name: kube2py-blue
 namespace: todoapp
 labels:
   app: kube2py-blue
  
spec:
 containers:
   - name: kube2py
     image: ikulyk404/kube2py:blue
     env:
     - name: EXTERNAL_ENDPOINT
       value: http://httpbin-api.mateapp.svc.cluster.local
     - name: APP_ENV
       value: "BLUE"
     resources:
       requests:
         memory: "64Mi"
         cpu: "30m"
       limits:
         memory: "64Mi"
         cpu: "30m"
     ports:
     - containerPort: 8080
     